"""
Alert model — a rule-based risk notification for a field (e.g. stripe rust
proliferation risk from a humid/warm weather window).

Generated by the alert engine sweep (services/alert_engine.py), one row per
triggered rule per field. `dismissed` covers the design's dismissible
dashboard banner + bell dropdown; there's no separate "read" state.
"""

import enum
import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional

from sqlalchemy import Boolean, DateTime, Enum as SAEnum, Float, ForeignKey, Index, String, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.field import Field


class AlertCategory(str, enum.Enum):
    pest = "pest"
    weather = "weather"
    price = "price"


class Alert(Base):
    __tablename__ = "alerts"
    __table_args__ = (
        # At most one ACTIVE (non-dismissed) alert per field+category —
        # matches _has_active_alert's app-level check in alert_engine.py, as
        # a real DB backstop against the sweep somehow inserting twice (e.g.
        # two overlapping sweep runs). Partial, not a plain UniqueConstraint,
        # because re-triggering after a dismissal is intentional: a
        # dismissed row must not block a fresh one.
        Index(
            "uq_alerts_active_field_category",
            "field_id",
            "category",
            unique=True,
            postgresql_where=text("dismissed = false"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    field_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("fields.id", ondelete="CASCADE"), nullable=False, index=True
    )

    category: Mapped[AlertCategory] = mapped_column(
        SAEnum(AlertCategory, name="alert_category", native_enum=True), nullable=False
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(String, nullable=False)
    risk_pct: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    dismissed: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )

    field: Mapped["Field"] = relationship("Field")

    def __repr__(self) -> str:
        return f"<Alert id={self.id} field_id={self.field_id} category={self.category}>"
