"""add reset_otp fields to users

Revision ID: 979b1db2b31e
Revises: 9d4b6e2a1f57
Create Date: 2026-08-26 17:45:42.710654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979b1db2b31e'
down_revision: Union[str, Sequence[str], None] = '9d4b6e2a1f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_plans_slug'), 'plans', type_='unique')
    op.drop_index(op.f('ix_plans_slug'), table_name='plans')
    op.create_index(op.f('ix_plans_slug'), 'plans', ['slug'], unique=True)
    op.drop_constraint(op.f('uq_user_subscriptions_user_id'), 'user_subscriptions', type_='unique')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=True)
    op.add_column('users', sa.Column('reset_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'reset_otp_expires')
    op.drop_column('users', 'reset_otp')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_plans_slug'), table_name='plans')
    op.create_index(op.f('ix_plans_slug'), 'plans', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_plans_slug'), 'plans', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
